# Generated by Django 4.2.4 on 2023-08-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art_gallery.category'),
        ),
    ]
