# Generated by Django 4.2.4 on 2023-08-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0002_artpiece_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductInCart',
        ),
    ]
